### ISSUE TITLE
Cant Bind files, no such File or directory

### ISSUE THREAD

**Issue by UltraBlackLinux** [jesseduffield/horcrux#11]
[maus@lolcat bind]$ tree
.
├── folder
│   ├── split_1_of_3.horcrux
│   ├── split_2_of_3.horcrux
│   └── split_3_of_3.horcrux
└── horcrux

1 directory, 4 files
[maus@lolcat bind]$ ./horcrux bind folder/
2020/07/13 08:49:03 open split_1_of_3.horcrux: no such file or directory

How do I solve this Problem?
Thanks!

**Comment by jesseduffield** [comment]
Should be fixed in https://github.com/jesseduffield/horcrux/pull/13 :)

**Comment by UltraBlackLinux** [comment]
Thanks!
