### ISSUE TITLE
Split number of files as argument

### ISSUE THREAD

**Issue by proyb6** [jesseduffield/horcrux#2]
It's prefer to set number of files to be split as argument Instead of a question.

`-number 33`

**Comment by jesseduffield** [comment]
I've added an `-n` flag for this, as well as a `-t` flag for setting the threshold. I'd prefer to use a package like flaggy to make it a little nicer (accepting different flag names for the same variable, not caring about where positional args are stored) but I don't want to have any dependencies (and I'm slightly lazy) so I'm just using -n for now (and keeping the prompt if you don't use the flag)
